
#WARNING: THIS IS JUST AN EXAMPLE FROM CLAUDE: NEEDS TO ADAPT TO THE PROJECT. 

version: '3'

services:
  finance-bot-app:
    build: ./app
    ports:
      - "1010:5000"  # Map container port 5000 to host port 1010
    environment:
      - PHI_MODEL_URL=http://phi-model:5000
      - GEMMA_MODEL_URL=http://gemma-model:5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - phi-model
      - gemma-model

  phi-model:
    build: ./phi-model
    ports:
      - "1011:5000"  # Map container port 5000 to host port 1011
    volumes:
      - ./models/phi3:/models

  gemma-model:
    build: ./gemma-model
    ports:
      - "1012:5000"  # Map container port 5000 to host port 1012
    volumes:
      - ./models/gemma3-4b:/models
